// <auto-generated />
using System;
using HouseHoldEmission.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseHoldEmission.Migrations
{
    [DbContext(typeof(HouseHoldDbContext))]
    [Migration("20250416095711_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseHoldEmission.Model.HouseHoldEntity", b =>
                {
                    b.Property<int>("HouseHoldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HouseHoldId"));

                    b.Property<double>("CoalUsage")
                        .HasColumnType("float");

                    b.Property<double>("ElectricityUsage")
                        .HasColumnType("float");

                    b.Property<double>("HouseHoldEmission")
                        .HasColumnType("float");

                    b.Property<double>("LPGUsage")
                        .HasColumnType("float");

                    b.Property<DateOnly>("RecordedDate")
                        .HasColumnType("date");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HouseHoldId");

                    b.ToTable("HouseHoldEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
